# specify site authors in this file
# you can add .yml files for any other global data in this folder

services:
- title: Development Services
  icon: ti-settings
  list: 
    - Software Development
    - Bespoke Business Applications
    - Web Application Development
    - Mobile App Development
    - Bespoke CRM Systems
    - Bespoke CMS Systems
    - Customer Portal Software
    - Hardware Integration
    - Machine learning &amp; AI
    - Realtime software

- title: Creative Services
  icon: ti-ruler-pencil
  list:
    - UI and UX Services
    - Front-end Design &amp; Development
    - Photography
    - Video Production
    - Digital Marketing &amp; SEO
    - Aerial Video &amp; Photography
    - Email marketing
    - eCommerce
    - Social media
    - Print Design


- title: Server Management &amp; DevOps
  icon: ti-dashboard
  list:
    - Data Migration
    - Operational Systems
    - Legacy Software Modernisation
    - Data Recovery
    - Cyber Security
    - Secure Global Hosting
    - Cloud Migration