# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/images" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - label: "Author"
        name: "author"
        widget: "select"
        options:
          - { label: "Matt", value: "matt" }
          - { label: "Jacob", value: "jacob" }
          - { label: "Mike", value: "mike" }
          - { label: "Darren", value: "darren" }
          - { label: "Seth", value: "seth" }
          - { label: "Phill", value: "phill" }
          - { label: "Rob", value: "rob" }
          - { label: "Tom", value: "tom" }
          - { label: "Sean", value: "sean" }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:MM:SS"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - { label: "Categories", 
          name: "categories", 
          widget: "select",
          options: ["development", "design", "server-management", "SEO", "Consultancy"], 
        }
      - {label: "Post Image", name: "image", widget: "image"}
    # PAGES
  - name: "page"
    label: "Page"
    folder: "pages"
    sort: "title:asc"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "hidden", required: false }
      # - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      # - {label: "Body", name: "body", widget: "markdown", required: false}

    # home page
  - name: "home"
    label: "Home"
    folder: "pages"
    sort: "title:asc"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      # - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "About section text", name: "about-text", widget: "markdown", required: false}
      - {label: "About section title", name: "about-title", widget: "string", required: false}
      - {label: "About link", name: "about-link", widget: "string", required: false}
      - {label: "About link text", name: "about-link-text", widget: "string", required: false}
      - {label: "Permalink", name: "permalink", widget: "hidden", required: false }
      # - {label: "Team section title", name: "team-title", widget: "string", required: false}
      # - {label: "Team section text", name: "team-text", widget: "markdown", required: false}
      # - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
      # - {label: "Body", name: "body", widget: "markdown", required: false}

    # team members
  - name: "team"
    label: "Team Members"
    folder: "_team"
    sort: "name:asc"
    create: true
    identifier_field: name
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "name", name: "name", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "image", name: "image", widget: "image"}
      - {label: "Permalink", name: "permalink", widget: "hidden" }

    # jobs
  - name: "job"
    label: "Post Job Vacancy"
    folder: "_jobs"
    sort: "title:asc"
    create: true
    identifier_field: title
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "recruit"}
      - {label: "Job Title", name: "title", widget: "string"}
      - {label: "Details", name: "details", widget: "text"}
      - {label: "How to apply", name: "how-to-apply", widget: "text"}
      - {label: "Closing date", name: "closing-date", widget: "datetime", format: "YYYY-MM-DD HH:MM:SS", required: false}
      - {label: "Permalink", name: "permalink", widget: "hidden" }
      - label: Requirments
        name: requirments
        widget: list
        required: false
        default: "Eg. Typescript"
        field: {label: "Requirment", name: "requirment", widget: "string", }

    # Projects
  - name: "projects"
    label: "Projects"
    folder: "_projects"
    sort: "project-name:asc"
    create: true
    identifier_field: project-name
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "project" }
      - { label: "Project name", name: "project-name", widget: "string" }
      - { label: "Project Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:MM:SS"}
      - { label: "Industry", name: "industry", widget: "string" }
      - { label: "Client", name: "client", widget: "string" }
      - { label: "Service", name: "service", widget: "string", required: false}
      - { label: "Project Link", name: "project-link", widget: "string", required: false}
      - { label: "Category", 
          name: "category", 
          widget: "select",
          options: ["development", "design", "server-management", "SEO", "Consultancy"]}
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Permalink", name: "permalink", widget: "hidden" }
      - label: "Gallery"
        name: "gallery"
        widget: "object"
        fields: 
          - label: Images
            name: galleryImages
            widget: list
            fields:
              - { label: Image, name: image, widget: image }
